# Generated by Django 2.1.7 on 2019-04-12 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplexFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lemma', models.TextField()),
                ('etymology', models.TextField()),
                ('semantics', models.TextField()),
                ('slavic_dict', models.TextField()),
                ('orig_srcs', models.TextField()),
                ('citation', models.TextField()),
                ('add_philol', models.TextField()),
                ('add_histor', models.TextField()),
                ('lang', models.TextField()),
            ],
            options={
                'managed': False,
                'db_table': 'complex_fields',
            },
        ),
        migrations.CreateModel(
            name='SimpleFields',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('lemma_rus', models.TextField()),
                ('pos', models.TextField()),
                ('lemma_greek', models.TextField()),
                ('if_hapax', models.TextField()),
                ('if_middle_lang', models.TextField()),
                ('vasmer', models.TextField()),
                ('translated_srcs', models.TextField()),
                ('rewrit_date', models.TextField()),
                ('orig_creation', models.TextField()),
                ('theme', models.TextField()),
                ('lang', models.TextField()),
            ],
            options={
                'managed': False,
                'db_table': 'simple_fields',
            },
        ),
        migrations.CreateModel(
            name='Sources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lemma', models.TextField()),
                ('source', models.TextField()),
                ('type', models.TextField()),
                ('lang', models.TextField()),
            ],
            options={
                'managed': False,
                'db_table': 'sources',
            },
        ),
        migrations.CreateModel(
            name='Variants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lemma', models.TextField()),
                ('var_type', models.TextField()),
                ('variant', models.TextField()),
                ('lang', models.TextField()),
            ],
            options={
                'managed': False,
                'db_table': 'variants',
            },
        ),
    ]
